version: '3.8'

services:
  # Aplicación web Athena Pocket
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - athena-network

  # PostgreSQL (para cuando implementes backend)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: athena_pocket
  #     POSTGRES_USER: athena_user
  #     POSTGRES_PASSWORD: athena_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - athena-network

  # Redis (para cuando implementes cache)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - athena-network

networks:
  athena-network:
    driver: bridge

# volumes:
#   postgres_data:
